### ISSUE TITLE
thorchainspam does not recover from errors

### ISSUE THREAD

**Issue by philipstanislaus** [thorchain/THORChain#21]
**Describe the bug**
`thorchainspam txs send` increases the internal sequence no matter whether checkTx fails or succeeds.

**How to reproduce**

1. Start local validator
1. create accounts: `thorchainspam account ensure --from deployer --k 20 --amount 200RUNE --chain-id genesis-alpha --spam-prefix spam2 --spam-password 1234567890 --sign-password 1234567890`
1. run spam `thorchainspam txs send --chain-id genesis-alpha --spam-prefix spam2 --spam-password 1234567890`
1. Wait until the error occurs. On my MacBook, after 14 minutes, the first spammer ran out of coins. After 18 minutes, all 20 spammers ran out of coins. They can never recover from that error, since sequences will be off afterwards no txs were send anymore.

**Expected behavior**
Should not increment cached sequence number if checkTx fails

**Comment by musnit** [comment]
script will pause and resync every time checkTx error is encountered
