### ISSUE TITLE
thorchainspam ensure account script uses wrong sequence

### ISSUE THREAD

**Issue by philipstanislaus** [thorchain/THORChain#22]
**Describe the bug**
```
I[09-04|16:03:29.631] Rejected bad transaction                     module=mempool tx=28CB2911DF962E85C10868EC8997D9DF800CF7EA res="&{CheckTx:code:65539 log:\"=== ABCI Log ===\\nCodespace: 1\\nCode:      3\\nABCICode:  65539\\nError:     --= Error =--\\nData: common.FmtError{format:\\\"Invalid sequence. Got 19, expected 0\\\", args:[]interface {}(nil)}\\nMsg Traces:\\n--= /Error =--\\n\\n=== /ABCI Log ===\\n\" fee:<> }"
```

**To Reproduce**

1. `thorchaind unsafe_reset_all`
1. Use the following genesis.json (adjust accounts so you are the 1 validator and staker): https://gist.github.com/philipstanislaus/a0fa4cf44a8ef8f0f129aa1df9c9c081 
1. Create local validator: `thorchaind start`
1. Run `thorchainspam account ensure --from deployer --k 20 --amount 200RUNE --chain-id genesis-alpha --spam-prefix spam3 --spam-password 1234567890 --sign-password 1234567890`

**Expected behavior**

Sequence should be set properly

**Comment by musnit** [comment]
Script will resync every 50k transactions
